name: coverage

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "33 16 * * *"

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [ 18.x ]
        os: [ubuntu-latest]

    services:
      odata-v4-cap-demo:
        image: theosun/odata-v4-cap-demo:latest
        ports:
          - 50031:3000

    steps:
      - name: Set git to use LF to checkout
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - run: npm ci
      - name: coverage
        run: npm run coverage
        env:
          C4C_ODATA: ${{ secrets.C4C_ODATA }}
          C4C_USER: ${{ secrets.C4C_USER }}
          C4C_PASS: ${{ secrets.C4C_PASS }}
          TEST_OAUTH_TOKEN_URL: ${{ secrets.TEST_OAUTH_TOKEN_URL }}
          TEST_OAUTH_CLIENT_ID: ${{ secrets.TEST_OAUTH_CLIENT_ID }}
          TEST_OAUTH_CLIENT_SECRET: ${{ secrets.TEST_OAUTH_CLIENT_SECRET }}
          CAP_DEMO_SERVICE: http://localhost:50031

      - name: Codecov
        uses: codecov/codecov-action@v3.1.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
